// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXs6Rso7q1In2T9iTCXCZlnfNXPRN8eRA',
    appId: '1:991777543724:web:5ef671f4566675b6f72389',
    messagingSenderId: '991777543724',
    projectId: 'gabut-a412c',
    authDomain: 'gabut-a412c.firebaseapp.com',
    storageBucket: 'gabut-a412c.firebasestorage.app',
    measurementId: 'G-71E6Z5T6PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIjpLsXVzhupHG-f7KmE4bBrgkhWaBr2U',
    appId: '1:991777543724:android:b9a7436cfc921ba8f72389',
    messagingSenderId: '991777543724',
    projectId: 'gabut-a412c',
    storageBucket: 'gabut-a412c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCalqNNjA_WqUUH85Gi0BVx-pp6bSYq7Q',
    appId: '1:991777543724:ios:a289c0ac046f478df72389',
    messagingSenderId: '991777543724',
    projectId: 'gabut-a412c',
    storageBucket: 'gabut-a412c.firebasestorage.app',
    iosBundleId: 'com.example.gabutTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCalqNNjA_WqUUH85Gi0BVx-pp6bSYq7Q',
    appId: '1:991777543724:ios:a289c0ac046f478df72389',
    messagingSenderId: '991777543724',
    projectId: 'gabut-a412c',
    storageBucket: 'gabut-a412c.firebasestorage.app',
    iosBundleId: 'com.example.gabutTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXs6Rso7q1In2T9iTCXCZlnfNXPRN8eRA',
    appId: '1:991777543724:web:e282489a4c8edd76f72389',
    messagingSenderId: '991777543724',
    projectId: 'gabut-a412c',
    authDomain: 'gabut-a412c.firebaseapp.com',
    storageBucket: 'gabut-a412c.firebasestorage.app',
    measurementId: 'G-VMNYJ4VQ72',
  );

}