// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8UcxoARGFnvHI8z96eGcIQfQ0CXMma4I',
    appId: '1:156533796355:web:61ae6f01cf474c2e8c2836',
    messagingSenderId: '156533796355',
    projectId: 'sira-projects',
    authDomain: 'sira-projects.firebaseapp.com',
    storageBucket: 'sira-projects.firebasestorage.app',
    measurementId: 'G-WYGSQG90LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkFW89L2b4V3AJzwEGMlQGWD1ck6j4Ht0',
    appId: '1:156533796355:android:e27d8171a2c1bf878c2836',
    messagingSenderId: '156533796355',
    projectId: 'sira-projects',
    storageBucket: 'sira-projects.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyQfKIim6q5fcRV0hTdrNJPXBBkka4h4',
    appId: '1:156533796355:ios:6b59b419517248cf8c2836',
    messagingSenderId: '156533796355',
    projectId: 'sira-projects',
    storageBucket: 'sira-projects.firebasestorage.app',
    iosBundleId: 'com.example.siraProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdyQfKIim6q5fcRV0hTdrNJPXBBkka4h4',
    appId: '1:156533796355:ios:6b59b419517248cf8c2836',
    messagingSenderId: '156533796355',
    projectId: 'sira-projects',
    storageBucket: 'sira-projects.firebasestorage.app',
    iosBundleId: 'com.example.siraProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8UcxoARGFnvHI8z96eGcIQfQ0CXMma4I',
    appId: '1:156533796355:web:89d03616e6b4bff58c2836',
    messagingSenderId: '156533796355',
    projectId: 'sira-projects',
    authDomain: 'sira-projects.firebaseapp.com',
    storageBucket: 'sira-projects.firebasestorage.app',
    measurementId: 'G-WKK1PNQH6R',
  );

}